---
title: "Joseph Turner CV"
author: Joseph Turner
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'custom2.css',  'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
library(googlesheets4)
source("C:/Users/JoeTurner/Documents/GitHub/cv/cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "C:/Users/JoeTurner/Documents/GitHub/cv/turner_cv_data_",  
  pdf_mode = params$pdf_mode
)

CV$entries_data <- CV$entries_data %>% dplyr::filter(in_resume == TRUE)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================
Joseph Turner {#title}
--------------------------------------------------------------------------------

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


Technical Skills {#skills}
--------------------------------------------------------------------------------

- Proficient:

  - R
  - Python
  - ESRI GIS Products
  - QGIS
  - GitHub

- Working knowledge:
  - Javascript
  - SQL 

Main
================================================================================

Professional Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('experience')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Interests {data-icon=info-circle}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('interests')
```


::: aside


Made with the R packages **pagedown** and **datadrivencv**.

The source code is available **github.com/jt-tbc/cv**.

Last updated on `r Sys.Date()`.

:::
